[package]
name = "app-rust-blockchain"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libsodium-sys = "0.2.7"
blake3 = "1.3.1"
regex = "1.6.0"
thousands = "0.2.0"